#!/bin/bash

get_fd() {
    local x
    local tmpfile
    local _fd_var=$1
    
    for x in $(seq 10 $(ulimit -n)); do
        if [[ ! -a "/proc/$BASHPID/fd/$x" ]]; then
            tmpfile=$(mktemp /dev/shm/XXX.tmp)
            exec {x}<>$tmpfile 
            printf -v "$_fd_var" %s "$x"
            rm $tmpfile
            return
        fi
    done
    echo 0
}

get_fd conffile

PROXYCHAINS_BIN="proxychains4"

if [[ "$1" == "-q" ]]; then
    shift
    QUIET="-q"
else
    echo "Use proxy ${1}://${2}:${3}"
    echo ""
fi

if [ ! $3  ] ; then
    echo No enough arguments!
    exit 1
fi


#cd "$TMPPATH"
cat << EOF >&$conffile

# proxychains.conf  VER 4.x
strict_chain
proxy_dns 
#remote_dns_subnet 127 
#remote_dns_subnet 10
remote_dns_subnet 224
# Some timeouts in milliseconds
tcp_read_time_out 15000
tcp_connect_time_out 8000

localnet 127.0.0.0/255.0.0.0
# localnet 10.0.0.0/255.0.0.0
# localnet 172.16.0.0/255.240.0.0
# localnet 192.168.0.0/255.255.0.0

[ProxyList]
$1 $2 $3

EOF

shift 3
if [[ ! $QUIET ]]; then
    echo "Apply proxy to command: $@"
    echo ""
fi

"$PROXYCHAINS_BIN" $QUIET -f /dev/fd/$conffile $@
result=$?

if [[ ! $QUIET ]]; then
    echo ""
    echo "...proxychains process finished."
fi

exit $result
